// Auto-generated by scripts/build-changelog.js from CHANGELOG.md -- do not edit by hand.
window.CHANGELOG_MARKDOWN = `# Changelog

8/25/26

-	Most site functions done

## Unreleased

-   Added an About tab with a live changelog, an about-me blurb, and suggestion/bug report boxes.
`;
